const RESPONSE_MESSAGE = {
    INVALID_JSON: "JSON format is not valid",
    INVALID_ROLE: "Invalid Role",
    BLOCK_ACCOUNT: "Account has been blocked for next 5 minutes",
    ACCOUNT_DISABLE: "Account is currently disable", 
    EMAIL_ALREADY_EXISTS: "Email already exists",
    PHONE_NUMBER_ALREADY_EXISTS: "Phone Number already exists",
    EMAIL_DOESNT_EXIST: "Email doesn't exists",
    FAILED_TO_SIGNUP: "Failed to signup",
    SIGNUP_SUCCESSFUL: "Successfully signup",
    FAILED_TO_LOGIN: "Failed to Login",
    LOGIN_SUCCESSFUL: "Successfully login",
    INVALID_CREDENTIAL: "Invalid Credential",
    INVALID_AUTHOR: "Invalid author",
    FAILED_TO_GET_AUTHORS: "Failed to get authors data",
    FAILED_TO_GET_SINGLE_AUTHORS: "Failed to get author data",
    FAILED_TO_ADD_AUTHOR: "Failed to add author",
    AUTHOR_DONT_EXISTS: "Author don't exists",
    AUTHOR_NAME_EXISTS: "Author already exists",
    AUTHOR_ADDED: "Author added successfully",
    FAILED_TO_GET_USERS: "Failed to get users data",
    FAILED_TO_GET_SINGLE_USER: "Failed to get user data",
    USER_NOT_FOUND: "User not found",
    FAILED_TO_UPDATE_USER: "Failed to update user",
    GET_ALL_USERS: "Successfully get all users data",
    GET_USER: "Successfully get all user data",
    FAILED_TO_DELETE_USER: "Failed to delete user",
    FAILED_TO_UPDATE_USER_BALANCE: "Failed to update user balance",
    USER_BALANCE_UPDATED: "Successfully updated user balance",
    DELETE_USER: "Successfully deleted user",
    USER_UPDATED: "Successfully updated user",
    PHONE_NUMBER_NOT_UNIQUE: "Phone number is not unique",
    GET_ALL_AUTHORS: "Successfully get all authors data",
    GET_AUTHOR: "Successfully get author data",
    UNAVAILABLE_BOOKS: "Some books are unavailable",
    INVALID_SORT_PROPERTY: "Invalid sorting property",
    FAILED_TO_GET_BOOKS: "Failed to get books data",
    FAILED_TO_GET_SINGLE_BOOK: "Failed to get book data",
    FAILED_TO_ADD_BOOK: "Failed to add book",
    FAILED_TO_UPDATE_BOOK: "Failed to update book",
    BOOK_ADDED: "Book added successfully",
    BOOK_UPDATED: "Book updated successfully",
    BOOK_EXISTS: "Book already exists",
    BOOK_DONT_EXISTS: "Book don't exists",
    GET_ALL_BOOKS: "Successfully get all books data",
    GET_BOOK: "Successfully get book data",
    FAILED_TO_DELETE_BOOK: "Failed to delete book",
    BOOK_DELETED: "Successfully deleted book",
    FAILED_TO_UPDATE_CART: "Failed to update cart",
    FAILED_TO_ADD_ITEM_TO_CART: "Failed to add book to cart",
    FAILED_TO_REMOVE_ITEM_TO_CART: "Failed to remove book to cart",
    CART_DONT_EXISTS: "Cart don't exists",
    CART_EMPTY: "Cart is empty",
    BOOK_DONT_EXISTS_IN_CART: "Book don't exists in the cart",
    BOOK_QUANTITY_DONT_EXISTS_IN_CART: "Book don't exists in the cart",
    ADD_ITEM_TO_CART: "Successfully add book to cart",
    REMOVE_ITEM_FROM_CART: "Successfully remove book from cart",
    FAILED_TO_VIEW_FROM_CART: "Failed to view your cart",
    GET_USER_CART: "Successfully viewed your cart",
    FAILED_TO_GET_DISCOUNTS: "Failed to get discounts data",
    FAILED_TO_DELETE_DISCOUNT: "Failed to delete discount data",
    DISCOUNT_NOT_FOUND: "Discount don't exists",
    DISCOUNT_DELETED_SUCCESSFULLY: "Successfully deleted discount",
    FAILED_TO_ADD_DISCOUNT: "Failed to add new discount",
    FAILED_TO_UPDATE_DISCOUNT: "Failed to update discount",
    GET_DISCOUNTS: "Successfully get all discounts",
    DISCOUNT_ADDED_SUCCESSFULLY: "Successfully added discount",
    DISCOUNT_UPDATED_SUCCESSFULLY: "Successfully updated discount",
    DISCOUNT_ALREADY_EXISTS_FOR_BOOK: "Discount for some of these books is alrady on going",
    DISCOUNT_ALREADY_EXISTS_FOR_AUTHOR: "Discount for these author is alrady on going",
    FAILED_TO_CREATE_TRANSACTION: "Failed to proceed the transaction",
    CREATE_TRANSACTION: "Successfully proceed the transaction",
    INSUFFECIENT_BALANCE: "Insuffecient balance to proceed the transaction",
    OUT_OF_STOCK: "Out of Stock",
    FAILED_TO_GET_ALL_TRANSACTION: "Failed to get transactions data",
    PHONE_NUMBER_AND_ADDRESS_NEED_FOR_TRANSACTION: "Phone number & proper address is required for transaction",
    GET_ALL_TRANSACTIONS: "Successfully get all transactions data",
    FAILED_TO_GET_REVIEW: "Failed to get review",
    GET_REVIEW: "Successfully get review",
    FAILED_TO_ADD_REVIEW: "Failed to add review",
    ADD_REVIEW: "Successfully added review",
    REVIEW_EXISTS: "Your review already exists for this book",
    REVIEW_DONT_EXISTS: "Review don't exists",
    FAILED_TO_UPDATE_REVIEW: "Failed to update review",
    UPDATE_REVIEW: "Successfully updated review",
    FAILED_TO_DELETE_REVIEW: "Failed to delete review",
    DELETE_REVIEW: "Successfully deleted review",
    UNAUTHORIZED: "Authentication required",
    TOKEN_EXPIRE: "Login Again",
    FAILED_TO_DISABLE_USER: "Failed to update user's disability",
    DISABLE_USER: "Successfully update user's disability ",
    FAILED_TO_DISABLE_BOOK: "Failed to update book's disability",
    DISABLE_BOOK: "Successfully update book's disability ",
    FAILED_TO_DISABLE_AUTHOR: "Failed to update author's disability",
    DISABLE_AUTHOR: "Successfully update author's disability ",
};

module.exports = RESPONSE_MESSAGE;